### PR TITLE
FTMTree: Remove TTK_ENABLE_FTM_TREE_PROCESS_SPEED

### LINKED ISSUE #960: TTK_ENABLE_FTM_TREE_PROCESS_SPEED set to ON leads to error
**Describe the bug**

The `TTK_ENABLE_FTM_TREE_PROCESS_SPEED` Cmake variable has not been maintained and should be removed.
Setting this variable to `ON`  leads to a compiler error (when a **const** variable is updated)

**To Reproduce**

1. Set `TTK_ENABLE_FTM_TREE_PROCESS_SPEED` to `ON` at configure time.
1. Try to compile

**Expected behavior**

* [] Remove the deprecated variable and associated code OR
* [] Update the code so the process speed works AND add a CI build with this option

### PR DESCRIPTION
**Pull request by pierre-guillou**
This PR should fix #960 by removing the TTK_ENABLE_FTM_TREE_PROCESS_SPEED CMake key and associated code, as suggested by @CharlesGueunet.

Enjoy,
Pierre

### CODE REVIEW

File: core/base/ftmTree/FTMTree_MT.cpp [hunk 1]
```diff
@@ -1006,18 +1000,7 @@ SimplexId FTMTree_MT::trunkCTSegmentation(const vector<SimplexId> &trunkVerts,
 #ifdef TTK_ENABLE_OPENMP
 #pragma omp taskwait
```
Comment (julien-tierny) [inline core/base/ftmTree/FTMTree_MT.cpp:1001]: do we need to leave that here? @CharlesGueunet

File: core/base/ftmTree/FTMTree_MT.cpp [hunk 2]
```diff
@@ -1078,18 +1054,12 @@ SimplexId FTMTree_MT::trunkSegmentation(const vector<SimplexId> &trunkVerts,
...
-#ifdef TTK_ENABLE_FTM_TREE_PROCESS_SPEED
-#ifdef TTK_ENABLE_OPENMP
-#pragma omp atomic update
-#endif
-      tot += acc;
-#endif
     } // end task
   }
 #ifdef TTK_ENABLE_OPENMP
 #pragma omp taskwait
```
Comment (julien-tierny) [inline core/base/ftmTree/FTMTree_MT.cpp:1060]: same as above.

**Review by julien-tierny — COMMENTED** [review]
thanks for the PR Pierre!
I have a question regarding the remaining `taskwait`.
are they really needed?
@CharlesGueunet

File: core/base/ftmTree/FTMTree_MT.cpp (hunk 1 above)
Comment (vollia) [reply core/base/ftmTree/FTMTree_MT.cpp:1001]: a quick test without those lead me to a segfault, so I assume they are needed ^^

We need to ensure all tasks are finished before leaving this context, and I assume the `return` instruction is not enough in a `task` block to ensure so.

**Comment by julien-tierny** [comment]
alright, thanks a lot!
